services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: studentdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-react-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pdocker"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    container_name: springboot
    build:
      context: ./STUDENTAPI-SPRINGBOOT
      dockerfile: ../STUDENTAPI-FULLSTACK/backend.Dockerfile
    ports:
      - "2001:2000"
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure
    networks:
      - springboot-react-network

  frontend:
    container_name: react
    build:
      context: ./STUDENTAPI-REACT
      dockerfile: ../STUDENTAPI-FULLSTACK/frontend.Dockerfile
    ports:
      - "3001:80"
    depends_on:
      backend
    networks:
      - springboot-react-network

# Declare volumes
volumes:
  mysql-data:

# Define custom bridge network
networks:
  springboot-react-network:
    driver: bridge
